base/urls.py
from django.urls import path

from .views import ProjectListView, ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

urlpatterns = [
    path('', ProjectListView.as_view(), name='projects'),
    path('project/<uuid:pk>/', ProjectView.as_view(), name='project'),
    path('project-create/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<uuid:pk>/edit/', ProjectUpdateView.as_view(), name='project-edit'),
    path('project/<uuid:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
]

devStagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('base.urls')),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import ProfileListView, ProfileView, loginPage, logoutUser, SignUpView

urlpatterns = [
    path('', ProfileListView.as_view(), name='profiles'),
    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout')
]

base/models.py
import uuid

from django.db import models
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False, )

    def __str__(self):
        return self.name

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=500, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=400, blank=True, null=True)
    intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=400, blank=True, null=True)
    social_twitter = models.CharField(max_length=400, blank=True, null=True)
    social_linkedin = models.CharField(max_length=400, blank=True, null=True)
    social_website = models.CharField(max_length=400, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserSignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password1', 'password2']
        help_texts = {
            'username': None,
            'first_name': None,
            'email': None,
            'password1': None,
            'password2': None
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['first_name'].required = False

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib import messages
from django.urls import reverse_lazy

from .forms import UserSignupForm
from .models import Profile
from django.views.generic import ListView, DetailView, CreateView


class ProfileListView(ListView):
    model = Profile
    template_name = 'users/profiles.html'


class ProfileView(DetailView):
    model = Profile
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_skills'] = self.object.skill_set.exclude(description__exact="")
        context['other_skills'] = self.object.skill_set.filter(description__exact="")
        return context


class SignUpView(CreateView):
    form_class = UserSignupForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('profiles')
    success_message = 'Your profile was created successfully'


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'Login or password does not match ')


    return render(request, 'users/login.html')


def logoutUser(request):
    logout(request)
    messages.error(request, 'User was logout!')
    return redirect('login')

users/templates/users/login.html
{% extends 'main.html' %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Enter username"/>
        <input type="password" name="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"/>
        <input type="submit" value="Login"/>
    </form>

{% endblock content %}

users/templates/users/profile.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.intro }}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">

              {% if profile.social_github %}
                <li>
                  <a title="Github" href="https://{{ profile.social_github }}" target="_blank"><i class="zmdi zmdi-github-alt zmdi-hc-2x"></i></a>
                </li>
              {% endif %}

              {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="https://{{ profile.social_twitter }}" target="_blank"><i class="zmdi zmdi-twitter zmdi-hc-2x"></i></a>
                </li>
              {% endif %}

              {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="https://{{ profile.social_linkedin }}" target="_blank"><i class="zmdi zmdi-linkedin zmdi-hc-2x"></i></a>
                </li>
              {% endif %}

              {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="https://{{ profile.social_website }}" target="_blank"><i class="zmdi zmdi-globe zmdi-hc-2x"></i></a>
                </li>
              {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
             {{ profile.bio }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {% for top_skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ top_skill }}</h4>
                <p class="devSkill__info">{{ top_skill.description }}</p>
              </div>
            {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

              {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill }}</small>
                </span>
              {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project }}</h3>
                      <p><a class="project__author" href="{% url 'profile' profile.id %}">By {{ profile }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:'s' }})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                          <span class="tag tag--pill tag--main">
                            <small>{{ tag }}</small>
                          </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

     <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

        {% for user in object_list %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'profile' user.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ user.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{ user.name }}</h3>
                    <h5>{{ user.intro|slice:"60" }}</h5>
                  </div>
                </div>
                <p class="dev__info">
                    {{ user.bio|slice:"200" }}
                </p>
                <div class="dev__skills">
                    {% for skill in user.skill_set.all|slice:"5" %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ skill }}</small>
                      </span>
                    {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}


        </div>
      </div>
    </section>
  </main>
{% endblock content %}

users/templates/users/signup.html
{% extends 'main.html' %}

{% block content %}

    <h2>Sign up</h2>
    <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>


{#    <form method="post">#}
{#  {% csrf_token %}#}
{##}
{#  <label>{{ form.username.label }}</label>#}
{#  {{ form.username }}#}
{##}
{#  <label>{{ form.password1.label }}</label>#}
{#  {{ form.password1 }}#}
{##}
{#  <label>{{ form.password2.label }}</label>#}
{#  {{ form.password2 }}#}
{##}
{#  <input type="submit" value="Submit">#}
{#</form>#}

{% endblock content %}